name: ci

on:
  push:
    branches:
      - '*'

env:
  DOCKER_TAG: ${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/sganslandt/cv:$DOCKER_TAG